### ISSUE TITLE
DMAC_ARBITER에서 N_MASTER가 4가 아닐 때도 고려해서 설계해야 하나요?

### ISSUE THREAD

**Issue by bhkim003** [ECE4278/project1#2]
DATA_SIZE는 AXI 채널마다 바뀔 수 있으니 위에 선언한 DATZ_SIZE라는 것을 가지고 코드를 작성해야 하지만 DMAC_TOP에서 사용하는 ENGINE이 4개로 고정이라는 가정이라면 N_MASTER의 경우는 
DMAC_ARBITER 내에서 그냥 4개로 생각하고 코드를 짜도 되는 건가요?

10/20 00:50
답변 감사드립니다!!

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

4개로 생각하고 코드를 작성해도 감점사항 없습니다. PPT 그림 및 설명에서 DMAC_ENGINE은 4개라고 표현했기 때문입니다.
그리고 이런 가정하에서는 ARBITER 코드가 좀 더 간단해지기 때문에, 위와 같은 가정하에서 작성하는 것을 추천드립니다.
