### ISSUE TITLE
Mem(dst)의 ready신호를 출력하는 policy관련 문의

### ISSUE THREAD

**Issue by gju06051** [ECE4278/project1#3]
안녕하세요. SOC설계및실습 강의를 수강하고있는 2018312959 최보열입니다. 중간고사 대체 project1관련 문의가 있어서 issue를 발급하게 되었습니다.

제가 인지하고 있는 내용은 AXI정책이 slave가 ready를 high로, master가 valid를 high로 출력할 경우 channel의 data를 교환하고 있는 것으로 인지하고 있습니다. 또한 slave와 master는 독립적인 주체로 각각 ready나 valid를 high로 출력하는데 영향을 미치지 않는 것으로 이해하고 있습니다. 

그런데 Step3의 Arbiter를 설계하는 과정에서 동작이 제대로 되지 않아서 디버깅 하고자  TB및 dst로 사용되는 mem(=AXI_SLAVE)코드 내용을 살펴보았는데 아래 부분이 이해가 되지 않습니다. 

![image](https://user-images.githubusercontent.com/37738888/197189145-4093e6c5-506b-4de4-8162-9a1ff26e86ef.png)

해당 코드는 SIMv2/TB/AXI_SLAVE의 190번째 line으로 AR, R channel 부분 코드입니다. 여기서 기존의 S_R_IDLE state에서 S_R_ARREADY 및 다른 순차적인 state로 전이하기 위해서는 ar_ch.arvalid 값이 1로 high가 되어야 합니다. 결론은 master가 valid신호를 주지 않는다면 slave는 ready신호를 출력하는 경우가 없다는 것으로 판단됩니다. 

AXI에서 slave와 master가 각각 ready나 valid를 출력하는 것은 서로의 동작에 관련이 없는 걸로 인지하고 있습니다.  Slave와 Master module이 자체적으로 ready의 경우 data를 수용할 수 있는지, valid의 경우 알맞은 data를 출력할 수 있는지 판단해서 각각 ready와 valid를 high로 바꾸는 것으로 알고 있습니다. 

그런데 위의 코드의 경우 Master가 valid를 출력한다면 Slave가 ready를 출력하도록 되어있는데 
1) 제가 AXI동작을 잘못 알고 있는 것인지
2) 아니면 이것이 memory 동작을 구현해 놓기 위해서  Master valid -> Slave ready로 구현해 놓은 것인지
3) 2)가 맞다면(src가 valid를 주면 무조건적으로 dst로 valid가 전달되도록) 이를  고려해서 arbiter를 설계해야 되는 것인지 알려주시면 감사하겠습니다. 

긴 글 읽어주셔서 감사합니다. 

최보열 올림.

**Comment by dale40** [comment]
좋은 질문입니다.

우선 AXI spec을 보면
source가 ready를 기다린 다음에 valid를 띄우는 것은 금지되어 있는 반면,
destination이 valid를 기다린 다음에 ready를 띄우는 것은 허용됩니다.

이렇게 하는 이유는 
둘다 허용할 경우 source는 ready가 뜨기만을 기다리고, destination은 valid가 뜨기만을 기다려서 deadlock 상황이 발생할 수 있기 때문입니다.

P.S. 참고로 valid와 ready는 어느 채널이냐에 따라서 drive하는 주체가 달라지기 때문에 master/slave로 표시하지 않고 source/destination이라고 표시합니다.(예: AWVALID는 master가 source, BVALID는 slave가 source).


ARM AMBA4 AXI spec.
A.3.2.1.
- A source is not permitted to wait until READY is asserted before asserting VALID.
- A destination is permitted to wait for VALID to be asserted before asserting the corresponding READY.

![image](https://user-images.githubusercontent.com/10312505/197307545-4bc544b1-e2e8-4a42-940d-f682a98cb2dd.png)

**Comment by gju06051** [comment]
답변 감사합니다! 편안하신 하루 보내시길 바랍니다.

최보열 올림.
