### ISSUE TITLE
DMAC_TOP에서 arready_i 와 awready_i 신호는 어디서 들어오는 신호인가요!?

### ISSUE THREAD

**Issue by gpfla108** [ECE4278/project1#4]
안녕하세요. 박태원 조교님.

ar_arbiter에서 dst_ready_i는 DMAC_TOP의 arready_i와 연결되어있고,
aw_arbiter에서 dst_ready_i는 DMAC_TOP의 awready_i 와 연결이 되어있는데,
이 arready_i와 awready_i 신호가 변하지 않는데, 이것은 어디서 들어오는 신호인지 궁금합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

1. arready_i와 awaready_i신호가 변하지 않는데
-> 이 부분은 제가 의미를 이해 못 했습니다.

2. 어디서 들어오는 신호인지 궁금합니다.
   DMAC_TOP arready_i와 awready_i는 DMAC_TOP 입장에서 input 신호입니다. 그리고 DMAC_TOP 모듈을 테스트하기 위해 존재하는 testbench(DMAC_TOP_TB)에서 해당 모듈을 DUT로 삼아서 input 신호를 다른 신호들과 연결을 시킵니다. DMAC_TOP_TB에서 신호들을 확인해보면 DMAC_TOP 모듈의 arready_i는 ar_ch.arready와 연결되어 있고, awready_i는 aw_ch.awready와 연결되어 있는 것을 확인할 수 있습니다. 그리고 ar_ch, aw_ch은 interface로 선언되어 있으며 ar_ch, aw_ch은 각각 AXI_SLAVE의 ar_ch, aw_ch에 연결되어있습니다. 따라서 테스트하는 상황에서 DMAC_TOP의 arready_i와 awready_i 신호는 AXI_SLAVE로부터 들어오는 것으로 볼 수 있습니다.

이해가 안 되는 부분은 다시 문의주시기 바랍니다.

박태원 드림

**Comment by gpfla108** [comment]
이해했습니다! 감사합니다 조교님, 혹시 그러면 DMAC_ARBITER에서 dst_ready_i 신호의 동작이 약간 헷갈리는데, dst_ready_i 에 따라서 어떤 동작을 해야하나요!?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.
 
일단 dst는 DMAC_TOP 밖, src는 DMAC_TOP이라고 생각하시면 됩니다. (정확히 말하자면 dst는 ready 신호를 만들어내고, src는 valid 신호를 만듭니다.) 즉, dst_ready_i는  DMAC_TOP 밖에서부터 안으로 들어오는 ready 신호로, arbiter가 선택한 DMAC_ENGINE에 대응되는 src_ready_o에 dst_ready_i신호가 입력되도록 하면 됩니다. ready는 AXI_SLAVE가 만들어서 DMAC_TOP로 향하는 신호이기 때문에 이 점을 생각하시면서 작성하면 되겠습니다. 

이해가 안 되는 부분은 다시 문의주시기 바랍니다.

박태원 드림

**Comment by gpfla108** [comment]
이해했습니다! 감사합니다 조교님.
