### ISSUE TITLE
Fixed priority Arbiter의 경우

### ISSUE THREAD

**Issue by john2554** [ECE4278/project1#5]
1. Fixed priority Arbiter의 경우 질문 있습니다.
만약, CH1의 정보가 Arbiter로 입력되어 출력되고 있을 때 CH1의 ready신호가 돌아오기 전에,
CH1보다 우선순위인 CH0의 정보가 Arbiter로 입력되면 Arbiter는 CH1의 정보를 출력해야 하나요?
아니면, ready신호가 돌아오기 전까지 CH1의 정보를 출력해야 하나요?

**Comment by dale40** [comment]
일단 valid가 뜬 다음에는 ready를 통해 handshake가 발생할 때까지 정보를 바꾸면 안됩니다. 이는 AXI를 비롯해서 많은 프로토콜에서 지켜져야하는 규약입니다.

AXI spec A.3.2.1를 보면
the source must keep its information stable until the transfer occurs ....
라고 되어 있습니다.

![image](https://user-images.githubusercontent.com/10312505/198489320-383b45ff-ef4c-44eb-8101-ecbac55a1cd7.png)

그 결과, 일단 ch1가 선택이 되어서 valid를 내보내고 있으면, 도중에 ch0가 들어온다고 해도 도중에 바꾸면 안됩니다.
