### ISSUE TITLE
write의 handshake 시점

### ISSUE THREAD

**Issue by john2554** [ECE4278/project1#6]
DST에 데이터가  하나씩 밀려서 write 됐습니다. 
문제점을 해결하려고 waveform을 보니 정확히 언제가 write의 handshake인지 궁금했습니다.
어떤 Valid와 Ready의 handshake를 봐야 하는지 헷갈립니다.

Arbiter에서 dst_valid_o와 dst_ready_i 의 handshke일 때로 봐야 하나요?
아니면 dst_valid_o와 src_ready_o의 handshake로 봐야 하나요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

우선 늦은 답변 죄송합니다. DST 입장에서 생각해본다면 dst_valid_o와 dst_ready_i 신호를 확인하여 handshake를 할 때 transaction이 일어날 겁니다.

추가적인 질문이 있으면 다시 문의를 주시기 바랍니다.
박태원 드림
