### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by woockddus** [ECE4278/project1#8]
TB에서는 아비터에서 보낸 valid와 data신호를 받아서 ready를 띄우는 방식인가요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

아래 질문과 유사한 질문이니 해당 이슈를 참고하시기 바랍니다.
Issue https://github.com/ECE4278/project1/issues/3

이해가 안되는 부분이 있으면 질문 주세요.

박태원 드림
