### ISSUE TITLE
src data 입력에 관해 질문 있습니다.

### ISSUE THREAD

**Issue by S-JinLee** [ECE4278/project1#9]
안녕하세요 조교님 src data 입력에 관해 질문이 있습니다!
data입력 받는 것을 기준으로 작동하는 logic을 만들었는데
한 채널의 src_data_i가 다 처리되었다고 해도 계속해서 마지막 src_data가 입력되고 있는 것인지 아니면 이후 src_data가 0으로 바뀌는지 궁금합니다!
감사합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

src_data가 0으로 바뀐다는 표현을 제가 이해못해서 확답을 못하겠습니다. 

마감시간까지 얼마 안남았으니, 확실한 부분만 알려드리겠습니다. 해당 부분이 ppt와 스펙에서 요구하는 동작과 일치하기만 하면 동작에서의 감점은 없습니다. 따라서 질문하신부분이 ppt와 스펙조건에 맞는지 확인하시고 별도로 다른 말이 없는 경우에는 자유롭게 구현하시면 됩니다. (물론, 프로젝트 설명했을 때 언급했듯이, 시간을 가지고 약간의 차등 점수를 부여하기 때문에 이 부분 역시 고려는 하셔야합니다.)

**Comment by dale40** [comment]
아마 valid가 내려온 다음에 information이 여전히 유지되는지에 대한 질문 같은데,
이에 대한 답변은 valid가 내려온 다음에는 information이 더이상 유지되지 않는다 입니다.

waveform으로 설명하면
clk      : __--__--__--__--__--__--
valid  :  ___--------_____________
ready : ___--------_____________
info   :  xxx data   xxxxxxxxxxxx
으로 valid가 떠 있을 때만 information에 제대로된 data가 실리며,
valid가 내려오면 information은 이전 값이 될 수도 있고, 0이 될 수도 있고, 다른 transaction을 위한 데이터로 바뀔 수도 있습니다.

**Comment by S-JinLee** [comment]
답변해주셔서 감사합니다!
